spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/mainproject?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: root
        password: yourPassword
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
        show_sql: true
        properties:
            hibernate:
                format_sql: true
logging:
    level:
        org:
            springframework:
                orm:
                    jpa: DEBUG
server:
    servlet:
        encoding:
            force-response: true
jwt:
    secret-key: xzczxcjasndksandksadnsadnsajkdnsajkcnkxjznmcklzcmklzmlckxzkmmcklx
    access-token-expiration-minutes: 30
    refresh-token-expiration-minutes: 420
mail:
    address:
        admin: admin@gmail.com